modLoader="javafml"
loaderVersion="[37,)"
license="GNU GPL v3.0 https://github.com/bl4ckscor3/The-Plopper/blob/1.17/LICENSE.md"
issueTrackerURL="https://github.com/bl4ckscor3/The-Plopper/issues"

[[mods]]
	modId="theplopper"
	version="${file.jarVersion}"
	displayName="The Plopper"
	description='''A block that picks up items that are about to despawn.'''
	displayURL="https://curseforge.com/minecraft/mc-mods/the-plopper"
	authors="bl4ckscor3"

[[dependencies.theplopper]]
    modId="forge"
    mandatory=true
    versionRange="[37,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.theplopper]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.17,1.18)"
    ordering="NONE"
    side="BOTH"