modLoader="javafml"
loaderVersion="[46,)"
license="MIT https://github.com/bl4ckscor3/The-Plopper/blob/1.20/LICENSE"
issueTrackerURL="https://github.com/bl4ckscor3/The-Plopper/issues"

[[mods]]
	modId="theplopper"
	version="${file.jarVersion}"
	displayName="The Plopper"
	description='''A block that picks up items that are about to despawn.'''
	displayURL="https://curseforge.com/minecraft/mc-mods/the-plopper"
	authors="bl4ckscor3"

[[dependencies.theplopper]]
    modId="forge"
    mandatory=true
    versionRange="[46,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.theplopper]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20,1.21)"
    ordering="NONE"
    side="BOTH"