modLoader="javafml"
loaderVersion="[1,)"
license="MIT https://github.com/bl4ckscor3/The-Plopper/blob/1.20.4/LICENSE"
issueTrackerURL="https://github.com/bl4ckscor3/The-Plopper/issues"

[[mods]]
	modId="theplopper"
	version="${file.jarVersion}"
	displayName="The Plopper"
	description='''A block that picks up items that are about to despawn.'''
	displayURL="https://curseforge.com/minecraft/mc-mods/the-plopper"
	authors="bl4ckscor3"

[[dependencies.theplopper]]
    modId="neoforge"
    type="required"
    versionRange="[20.4.70-beta,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.theplopper]]
    modId="minecraft"
    type="required"
    versionRange="[1.20.4,1.21)"
    ordering="NONE"
    side="BOTH"