modLoader="javafml" #mandatory
loaderVersion="[33,)" #mandatory
license="GNU GPL v3.0 https://github.com/bl4ckscor3/The-Plopper/blob/1.16/LICENSE.md"

[[mods]] #mandatory
	modId="theplopper" #mandatory
	version="${version}" #mandatory
	displayName="The Plopper" #mandatory
	description='''A block that picks up items that are about to despawn.''' #mandatory
	issueTrackerURL="https://github.com/bl4ckscor3/The-Plopper/issues"
	displayURL="https://curseforge.com/minecraft/mc-mods/the-plopper"
	authors="bl4ckscor3"

[[dependencies.theplopper]]
    modId="forge"
    mandatory=true
    versionRange="[33,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.theplopper]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16,1.17)"
    ordering="NONE"
    side="BOTH"