modLoader="javafml"
loaderVersion="[44,)"
license="MIT https://github.com/bl4ckscor3/The-Plopper/blob/1.19/LICENSE.md"
issueTrackerURL="https://github.com/bl4ckscor3/The-Plopper/issues"

[[mods]]
	modId="theplopper"
	version="${file.jarVersion}"
	displayName="The Plopper"
	description='''A block that picks up items that are about to despawn.'''
	displayURL="https://curseforge.com/minecraft/mc-mods/the-plopper"
	authors="bl4ckscor3"

[[dependencies.theplopper]]
    modId="forge"
    mandatory=true
    versionRange="[44.0.6,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.theplopper]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.3,1.20)"
    ordering="NONE"
    side="BOTH"