modLoader="javafml" #mandatory
loaderVersion="[28,)" #mandatory

[[mods]] #mandatory
	modId="theplopper" #mandatory
	version="v1.2.4" #mandatory
	displayName="The Plopper" #mandatory
	description='''A block that picks up items that are about to despawn.''' #mandatory
	issueTrackerURL="https://github.com/bl4ckscor3/The-Plopper/issues"
	displayURL="http://minecraft.curseforge.com/projects/the-plopper"
	authors="bl4ckscor3"

[[dependencies.theplopper]]
    modId="forge"
    mandatory=true
    versionRange="[28.0.45,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.theplopper]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14,1.15)"
    ordering="NONE"
    side="BOTH"