license="MIT https://github.com/bl4ckscor3/The-Plopper/blob/1.21.11/LICENSE"
issueTrackerURL="https://github.com/bl4ckscor3/The-Plopper/issues"

[[mods]]
	modId="theplopper"
	version="${file.jarVersion}"
	displayName="The Plopper"
	description='''A block that picks up items that are about to despawn.'''
	displayURL="https://curseforge.com/minecraft/mc-mods/the-plopper"
	authors="bl4ckscor3"

[[mixins]]
    config="theplopper.mixins.json"

[[dependencies.theplopper]]
    modId="neoforge"
    type="required"
    versionRange="[21.11,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.theplopper]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.11,)"
    ordering="NONE"
    side="BOTH"